// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Page(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"us\"><head><meta charset=\"UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `resources/layouts/page.templ`, Line: 9, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - zoity</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://unpkg.com/htmx.org\"></script><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-[#F9EFE5] font-sans text-neutral-900 antialiased\"><main class=\"h-[100vh]\"><div class=\"bg-[#F9EFE5] h-full flex justify-center items-start pt-[5%]\"><div class=\"w-[90%] max-w-6xl h-[90%] bg-white border border-zinc-300 rounded-t-md flex flex-col overflow-hidden\"><div class=\"h-9 bg-zinc-100 border-b border-zinc-300 flex justify-between items-center px-4 text-xs\"><div class=\"flex items-center gap-2 mr-6\"><div class=\"flex items-center gap-2 font-semibold\"><div class=\"w-4 h-4 rounded-full border border-zinc-300 flex items-center justify-center text-[10px]\">Z</div><span>zoity.io</span></div><nav class=\"ml-6 flex gap-4 text-zinc-700\"><a class=\"hover:text-pink-700 font-medium\" href=\"/dashboard\">Dashboard</a> <a class=\"hover:text-pink-700 font-medium\" href=\"/services\">Services</a> <a class=\"hover:text-pink-700 font-medium\" href=\"/flows\">Flows</a> <a class=\"hover:text-pink-700 font-medium\" href=\"/settings\">Settings</a></nav></div><nav class=\"flex gap-4 text-zinc-700\"><a class=\"hover:text-pink-700 font-medium\" href=\"https://github.com/isaqueveras/zoity\" target=\"_blank\">Github</a> <a class=\"hover:text-pink-700 font-medium\" href=\"/exit\">Exit</a></nav></div><div class=\"flex-1 overflow-y-auto\"><div class=\"p-8 space-y-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
